apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandwidth
  labels:
    app.kubernetes.io/name: "bandwidth"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: "bandwidth"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "bandwidth"
    spec:
      containers:
        - name: tracker
          image: ghcr.io/meschbach/pfsense-bandwidth-tracker:v0.0.6
          ports:
            - containerPort: 2112
              name: http
          command: [ "/tracker","service", "-u", "user", "-p", "host", "-s", "password", "-n", "iface" ]
