apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bandwidth-monitor
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - bandwidth
  selector:
    matchLabels:
      app: bandwidth
